INSM/urls.py
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import *



urlpatterns = [#add_distribution

    path('INSMHome/'                               , INSMHOME                                , name='INSMHome'                       ),
 
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

INSServer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets



class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)






urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('ServerController.urls')),
    path('', include('INSM.urls')),
    path('', include('INSPP.urls')),
    

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ServerController/urls.py
from .views import *
from users.views import *
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', home,name='home'),
    path('profile/', profile,name='profile'),
    path('cc-inbox/', CCInboxMailView.as_view(),name='CCInboxMailView'),
    path('bcc-inbox/', BCCInboxMailView.as_view(),name='BCCInboxMailView'),
    path('outbox/', OutboxMailView.as_view(),name='OutboxMailView'),
    path('login/',  view_login, name='login' ),
    path('SET_SYNCH_USER/',  SET_SYNCH_USER, name='SET_SYNCH_USER' ),
    path('addFolder/?P<int:main_folder>/',  addFolder, name='addFolder' ),#main_personal_storage_API
    path('personal_storage/?P<int:folder>/',  personal_storage, name='personal_storage' ),
    path('main_personal_storage_API/',  main_personal_storage_API, name='main_personal_storage_API' ),
    path('personal_storage_API/<int:folder>/',  personal_storage_API, name='personal_storage_API' ),
    path('addFile/?P<int:main_folder>/',  addFile, name='addFile' ),
    path('replymail/?P<str:user_to>/?P<str:subject>/',  send_mail, name='replymail' ),
    path('sendmail/',  send_mail, name='sendmail' ),
    path('view_mail/',  view_mail, name='view_mail' ),
    path('mail-home/',  mail_home, name='mail_home' ),
    path('AccessDenied/',  accessDenied, name='accessDenied' ),
    path('mail/<int:pk>/', ReadMail.as_view(), name='readmail' ),
    path('file/<int:pk>/', FileView.as_view(), name='file' ),
    path('folder/<int:pk>/', FolderView.as_view(), name='folder' ),
    path('download/<int:file_pk>/', download_file , name='download_file' ),#
    path('settings/', Settings , name='settings' ),
    


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import datetime

class App(models.Model):
    name                    =  models.CharField( max_length=200)
    icon_path               =  models.CharField( max_length=200)
    home_path               =  models.CharField( max_length=200)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user                    =  models.OneToOneField(User, null=True, blank=True ,on_delete=models.CASCADE)
    database_code	        =  models.CharField( max_length=200, default=None,null=True, blank=True )
    user_app                =  models.ForeignKey(App, null=True, blank=True ,on_delete=models.CASCADE)
    mail_edited             =  models.CharField( max_length=20000, default='[]',null=True, blank=True )#when receved or readed
    storage_file_pk         =  models.IntegerField(default= 0)
    
    
    
    
    def __str__(self):
        return self.user.username




class mail(models.Model):
    username_from   =  models.ForeignKey(User, null=True, blank=True ,on_delete=models.CASCADE)
    subject         =  models.CharField( max_length=200, default=None,null=True, blank=True )
    body            =  models.TextField()
    sending_datetime=  models.DateTimeField()


class Mail_CC_Receiver(models.Model):
    mail        = models.ForeignKey(mail, null=True, blank=True ,on_delete=models.CASCADE)
    user        = models.ForeignKey(User, null=True, blank=True ,on_delete=models.CASCADE)
    readed      = models.BooleanField( default=False )
    DT          = models.DateTimeField(null=True, blank=True )
    created_date= models.DateTimeField(default= datetime.datetime.now())


class Mail_BCC_Receiver(models.Model):
    mail        = models.ForeignKey(mail, null=True, blank=True ,on_delete=models.CASCADE)
    user        = models.ForeignKey(User, null=True, blank=True ,on_delete=models.CASCADE)
    readed      = models.BooleanField( default=False )
    DT          = models.DateTimeField(null=True, blank=True )
    created_date= models.DateTimeField(default= datetime.datetime.now())


class Folder(models.Model):
    name            = models.CharField( max_length=200, default='New Folder')
    owner           = models.ForeignKey( User , null=True, blank=True ,on_delete=models.CASCADE)    
    privet          = models.BooleanField(default=True)
    MainFolder      = models.ForeignKey('self', null=True, blank=True ,on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name

class File(models.Model):
    name            = models.CharField( max_length=200, default='New file')
    file            = models.FileField(upload_to='users_files')
    owner           = models.ForeignKey( User , null=True, blank=True ,on_delete=models.CASCADE)    
    privet          = models.BooleanField(default=True)
    MainFolder      = models.ForeignKey(Folder, null=True, blank=True ,on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name

ServerController/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'username','style':''' color:white;background-color: #0e1621;border: 0px;  padding:5px;  border-radius: 6px;  margin-top: 2px;  margin-bottom: 20px;  width: 250px;  text-align:center;'''}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'password','style':''' color:white;background-color: #0e1621;border: 0px;  padding:5px;  border-radius: 6px;  margin-top: 2px;  margin-bottom: 20px;  width: 250px;  text-align:center;'''}))


class select_model_name(forms.Form):
    name = forms.CharField(max_length=100)


class SET_SYNCH_USER_FORM(forms.Form):
    username = forms.CharField(max_length=100)
    

ServerController/views.py
from django.shortcuts import render,redirect
import sys
import os
from django.contrib.auth import authenticate, login
from .forms import  *
from django import forms
from users.models import *
from INSServer import settings# import SYNCH_USER,SYNCH_TIMER
from django.contrib.auth.models import User
import time, threading
from django.http import FileResponse, HttpResponse, JsonResponse
import mimetypes
import os, configparser, sys
from django.conf import settings
from django.http import HttpResponse, Http404
from django.views.generic import DetailView  ,ListView
from django.core.management import execute_from_command_line

# Create your views here.
def home(request):
	if not request.user.is_authenticated:
		return redirect('login')
	else:
		return render(request , 'index.html' )


def profile(request):
    if not request.user.is_authenticated:
    	return redirect('login')
    else:
    	return render(request , 'profile.html' )


def Settings(request):
    print(dir(request))
    if not request.user.is_authenticated:
    	return redirect('login')
    elif request.user.profile.user_app.name == 'INSM':

    	config = configparser.ConfigParser()
    	config.read('settings.ini')

    	if request.method == 'POST':
    		if 'time_zone' in request.POST:
    			try:
    				config['INFO']['TZ_GMT'] = str(int(request.POST['value']))
    				config.write(open('settings.ini','w'))
    				settings.TIME_ZONE = 'Etc/GMT+'+ config['INFO']['TZ_GMT']

    			except:
    				pass

    			

    		if 'HOST_TYPE' in request.POST:
    			print(request.POST)
				
    			config['INFO']['HOST_TYPE'] = request.POST['type']
    			config.write(open('settings.ini','w'))
    			old_file = open( os.path.join('ServerController','admin.py'),'r').read()
    			open( os.path.join('ServerController','admin.py'),'w').write(old_file)

    			return render(render, 'server-reloading.html')


    		old_file = open( os.path.join('ServerController','admin.py'),'r').read()
    		open( os.path.join('ServerController','admin.py'),'w').write(old_file)


    		data = { 
				'TIME_ZONE_GMT' :  config['INFO']['TZ_GMT'],
				'HOST_TYPE' 	:  config['INFO']['HOST_TYPE'],
				'HOST_TYPES'	: ['Device', 'LAN', 'WAN'],
			}
    		return render(request , 'settings.html', data )


    	else:
    		data = {
				'TIME_ZONE_GMT' :  config['INFO']['TZ_GMT'],
				'HOST_TYPE' 	:  config['INFO']['HOST_TYPE'],
				'HOST_TYPES'	: ['Device', 'LAN', 'WAN'],
			}
    		return render(request , 'settings.html', data )

    else:
    	return redirect('accessDenied')


	

def mail_home(request):
    
    if not request.user.is_authenticated:
    	return redirect('login')
    else:
    	new_mails_ids = set.union( set(Mail_CC_Receiver.objects.filter(user = request.user,readed=False ).values_list('user', flat=True)) , set(Mail_BCC_Receiver.objects.filter(user = request.user,readed=False ).values_list('user', flat=True)))
    	print(new_mails_ids)
    	new_mails = mail.objects.filter(pk__in = new_mails_ids)
    	if len(new_mails)>3 :
    		new_mails_objects = new_mails[:3]
    	else:
    		new_mails_objects = new_mails


    	
    	mails = mail.objects.filter(username_from = request.user)
    	contacts_ids = set.union(
			set(Mail_CC_Receiver.objects.filter( mail__in = mails).values_list('user', flat=True)),
			set(Mail_BCC_Receiver.objects.filter( mail__in = mails).values_list('user', flat=True))
		)
    	contacts = User.objects.filter(pk__in = contacts_ids)

		
    	

    	return render(request , 'mail-home.html', { 'new_messages_count': 3 ,'new_messages': new_mails_objects, 'contacts':contacts } )



class CCInboxMailView(ListView):
	model 				= Mail_CC_Receiver
	context_object_name = 'mail'
	template_name 		= 'cc-inbox-mail.html'
	paginate_by			= 12
	ordering 			= ['-created_date']

	def get_queryset(self):
		queryset = super().get_queryset()
		return  queryset.filter(user = self.request.user)



class BCCInboxMailView(ListView):
	model 				= Mail_BCC_Receiver
	context_object_name = 'mail'
	template_name 		= 'bcc-inbox-mail.html'
	paginate_by			= 12
	ordering 			= ['-created_date']

	def get_queryset(self):
		queryset = super().get_queryset()
		return  queryset.filter(user = self.request.user)



class OutboxMailView(ListView):
	model 		= mail
	context_object_name = 'mail'
	template_name = 'outbox-mail.html'
	paginate_by=12
	ordering = ['-sending_datetime']

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(username_from=self.request.user)



def accessDenied(request):
    if not request.user.is_authenticated:
    	return redirect('login')
    else:
    	return render(request , 'accessDenied.html' )


def SYNCH_USER_TIMER(user):
	settings.SYNCH_USER = user

	while True:
		time.sleep(1)
		settings.SYNCH_TIMER=settings.SYNCH_TIMER-1
		
		if settings.SYNCH_TIMER <=0:
			break
	settings.SYNCH_USER = None



def SET_SYNCH_USER(request):
	if not request.user.is_authenticated:
		return redirect('login')
	else:
		if request.method == 'POST':
			username = SET_SYNCH_USER_FORM(request.POST).data['username']
			print(username,settings.SYNCH_USER == None)
			red = render(request, 'SET_SYNCH_USER.html', {'form': SET_SYNCH_USER_FORM()})


			if settings.SYNCH_USER == None:
				try:
					user = User.objects.get(username=username)
					settings.SYNCH_TIMER=40
					threading.Thread(target=SYNCH_USER_TIMER, args=(user,)).start()
					red.set_cookie(key ='status', value = 1)

				except:
					red.set_cookie(key ='status', value = 0)
			
			else:
				try:
					if settings.SYNCH_USER == User.objects.get(username=username):
						settings.SYNCH_TIMER=40
						red.set_cookie(key ='status', value = 1)
				except:

					red.set_cookie(key ='status', value = 0)
			
			return red
		else:
			return render(request, 'SET_SYNCH_USER.html', {'form': SET_SYNCH_USER_FORM()})


def view_login(request):
	
	if request.method == 'POST':
		form = UserLoginForm( data=request.POST )
		user = form.get_user()


		if form.is_valid(): 
			user = authenticate( username=form.data['username'], password=form.data['password'])
			print(user)
			if user is not None:
				login(request= request,user=user)
			try:
				
				if user.profile.database_code == None or user.profile.database_code == form.data['database_code']:
					if user.profile.database_code == None:
						profile=Profile.objects.get(user=user)
						print(profile.database_code)
						profile.database_code = form.data['database_code']
						profile.save()
					
					if user.profile.user_app.name == form.data['app']:
						return redirect('home')
					else:
						red = render(request, 'login.html' , {'form': form})
						re_app= form.data['app']
						red.set_cookie(key ='message', value = f'You are trying to login with {user.profile.user_app.name} account by { re_app } app')
						return red

				
				else:
					red = render(request, 'login.html' , {'form': form})
					red.set_cookie(key ='message', value = '''You can not connect to INSServer with this file <br/>make sure database code set correctly on server databases''')
					return red
			except:
					return redirect(user.profile.user_app.name+'Home')

		else:
			
			red = render(request, 'login.html' , {'form': form})
			red.set_cookie(key ='message', value = 'Access denied')
			return red


	if request.method == 'GET':
		form = UserLoginForm()

		return render(request, 'login.html' , {'form': form})



def personal_storage(request, folder):

	current_item = Folder.objects.get(pk = folder) 
	if current_item.owner == request.user or not current_item.privet:

		folders = Folder.objects.filter(MainFolder = folder)
		files 	= File.objects.filter(MainFolder = folder)

		if len(folders)==0 and len(files)==0 : 
			empty = True

		else:
			empty = False

		return render(request, 'personal_storage.html' , {'folders' : folders , 'files':files , 'current_item' : current_item , 'empty' : empty  } )
	
	else:
		return redirect('accessDenied')



def personal_storage_API(request, folder):

	current_item = Folder.objects.get(pk = folder) 
	if current_item.owner == request.user or not current_item.privet:

		folders = Folder.objects.filter(MainFolder = folder)
		files 	= File.objects.filter(MainFolder = folder)

		if len(folders)==0 and len(files)==0 : 
			empty = True

		else:
			empty = False

		API_folders = []
		API_files = []
		for folder in folders:
			API_folders.append(
				{
					'name'     	:folder.name,
					'pk'     	:folder.pk,
					'privet'    :folder.privet,
					'MainFolder':folder.MainFolder.pk,
				}
			)
		
		for file in files:
			API_files.append(
				{
					'name' : file.name,
					'pk' : file.pk,
					'file' : file.file.url,
					'privet' : file.privet,
					'MainFolder' : file.MainFolder.pk,
				}
			)

		out_data = {
				'name': current_item.name ,
				'folders' : API_folders , 
				'files':API_files }
			
		
		if current_item.MainFolder:
			

			if current_item.MainFolder.MainFolder:
				

				if current_item.MainFolder.MainFolder.MainFolder:
					out_data['p1_folder'] = current_item.MainFolder.MainFolder.MainFolder.pk
					out_data['p1_folder_name'] = current_item.MainFolder.MainFolder.MainFolder.name

					out_data['p2_folder'] = current_item.MainFolder.MainFolder.pk
					out_data['p2_folder_name'] = current_item.MainFolder.MainFolder.name

					out_data['p3_folder'] = current_item.MainFolder.pk
					out_data['p3_folder_name'] = current_item.MainFolder.name

				else:
					out_data['p1_folder'] = current_item.MainFolder.MainFolder.pk
					out_data['p1_folder_name'] = current_item.MainFolder.MainFolder.name

					out_data['p2_folder'] = current_item.MainFolder.pk
					out_data['p2_folder_name'] = current_item.MainFolder.name


			else:
				out_data['p1_folder'] = current_item.MainFolder.pk
				out_data['p1_folder_name'] = current_item.MainFolder.name


		print(out_data)


		return JsonResponse(out_data, safe=False)
	
	else:
		return redirect('accessDenied')



def main_personal_storage_API(request):
	folder = request.user.profile.storage_file_pk 

ServerController/templates/users/file_detail.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <title>INS | File </title>
  </head>
  {% include 'navbar.html' %}
<body class="body-style">
    <style>
      #filedrag
{
	display: none;
	font-weight: bold;
	text-align: center;
	padding: 1em 0;
	margin: 1em 0;
	color: #555;
	border: 2px dashed #555;
	border-radius: 7px;
	cursor: default;
}

#filedrag.hover
{
	color: #f00;
	border-color: #f00;
	border-style: solid;
	box-shadow: inset 0 3px 4px #888;
}
    </style>
    {% if form %}
    <form class="profile_out_form" method="POST" style="text-align: left;"  enctype="multipart/form-data"  >
      <a href="{% url 'personal_storage' form.instance.MainFolder.id %}" class="btn_style_1" style="display: inline-block;"> < </a>
      <h2 style="text-align: center;">File</h2>
        
        {% csrf_token %}
        <p style="width: 30%; display: inline-block;text-align: right;"> Name:   </p>{{ form.name|add_class:"field-style-2" }} <br>
        <div style="text-align: center;">
          {% if form.instance.file %}
            <p>  File: <a href="{{ form.instance.file.url }}" style="display: inline-block;text-align: left;width: min-content;color:cyan; text-decoration: none;">{{ form.instance.file.name|slice:"12:" }}  </a><small style="color: gray;">{{ form.instance.file.size }}</small><br></p> <br>
            
          {% endif %}
            
          <label class="btn_style_1" for="upload">Change File</label>
          
          <input type="file" name="file" id="upload" >
          <div id="file-upload-filename" style="margin-top: 20px;"></div>
        </div>
        <p style="width: 30%; display: inline-block;text-align: right;"> Privet:   </p>{{ form.privet}} <br>
        
        
        <button type="submit" class="btn_style_1" name="edit" value="Edit" style="display: inline-block;"><img src="{% static 'inspp-icons/edit.png' %}" alt="Add raw material" style="width: 30px;"></button>
        <div class="btn_style_1" id="myBtn" style="width: 30px;display: inline-block;"><img src="{% static 'inspp-icons/delete.png' %}" alt="Add raw material" style="width: 30px;"></div>
        <div id="myModal" class="modal">
          <div class="modal-content profile_out_form">
            <span class="close">&times;</span>
            <p>Are you sure Do you wannt to delete this?</p>
            <button type="submit" class="btn_style_1" name="delete" value="Delete" >YES</button>
          </div>
        </div>

    </form>
    {% endif %}
    {% if not form   %}
    <form class="profile_out_form" method="POST" style="text-align: left;"  enctype="multipart/form-data"  >
      <h2 style="text-align: center;">{{ object.name }}</h2>
        <div style="text-align: center;">
          {% if object.file %}
            <p>  File: <a href="{{ object.file.url }}" style="display: inline-block;text-align: left;width: min-content;color:cyan; text-decoration: none;">{{ object.file.name|slice:"12:" }}  </a><small style="color: gray;">{{ object.file.size }}</small><br></p>
            <p>  Owner: {{ object.owner }}</p> 
          {% endif %}
        </div>
    </form>
    {% endif %}

    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
  </body>
  <script>
    var input = document.getElementById( 'upload' );
    var infoArea = document.getElementById( 'file-upload-filename' );

    input.addEventListener( 'change', showFileName );

    function showFileName( event ) {
      
      // the change event gives us the input it occurred in 
      var input = event.srcElement;
      
      // the input has an array of files in the `files` property, each one has a name that you can use. We're just using the name here.
      var fileName = input.files[0].name;
      
      // use fileName however fits your app best, i.e. add it into a div
      infoArea.textContent = 'Selected file: ' + fileName;
    }

    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
    modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
    modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
    } 

</script>
</html>

ServerController/templates/users/folder_detail.html
  

        {% load static %}
        {% load widget_tweaks %}
        
        <!DOCTYPE html>
        <html lang="en" dir="ltr">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" href="{% static 'style/main.css' %}">
            <title>INS | File </title>
          </head>
          {% include 'navbar.html' %}
          <body class="body-style">
            <style>
              #filedrag
        {
          display: none;
          font-weight: bold;
          text-align: center;
          padding: 1em 0;
          margin: 1em 0;
          color: #555;
          border: 2px dashed #555;
          border-radius: 7px;
          cursor: default;
        }
        
        #filedrag.hover
        {
          color: #f00;
          border-color: #f00;
          border-style: solid;
          box-shadow: inset 0 3px 4px #888;
        }
            </style>
            {% if form %}
            <form class="profile_out_form" method="POST" style="text-align: left;"  enctype="multipart/form-data"  >
              <a href="{% url 'personal_storage' form.instance.MainFolder.id %}" class="btn_style_1" style="display: inline-block;"> < </a>
              <h2 style="text-align: center;">Folder</h2>
                
                {% csrf_token %}
                <p style="width: 30%; display: inline-block;text-align: right;"> Name:   </p>{{ form.name|add_class:"field-style-2" }} <br>
                <h2 id="upload" ></h2>
                <p style="width: 30%; display: inline-block;text-align: right;"> Privet:   </p>{{ form.privet}} <br>
                
                
                <button type="submit" class="btn_style_1" name="edit" value="Edit" style="display: inline-block;"><img src="{% static 'inspp-icons/edit.png' %}" alt="Add raw material" style="width: 30px;"></button>
                <div class="btn_style_1" id="myBtn" style="width: 30px;display: inline-block;"><img src="{% static 'inspp-icons/delete.png' %}" alt="Add raw material" style="width: 30px;"></div>
                <div id="myModal" class="modal">
                  <div class="modal-content profile_out_form">
                    <span class="close">&times;</span>
                    <p>Are you sure Do you wannt to delete this?</p>
                    <button type="submit" class="btn_style_1" name="delete" value="delete" >YES</button>
                  </div>
                </div>
        
            </form>
            {% endif %}
            {% if not form   %}
            <form class="profile_out_form" method="POST" style="text-align: left;"  enctype="multipart/form-data"  >
              <h2 style="text-align: center;">{{ object.name }}</h2>
                <div style="text-align: center;">
                  {% if object.file %}
                    <p>  File: <a href="{{ object.file.url }}" style="display: inline-block;text-align: left;width: min-content;color:cyan; text-decoration: none;">{{ object.file.name|slice:"12:" }}  </a><small style="color: gray;">{{ object.file.size }}</small><br></p>
                    <p>  Owner: {{ object.owner }}</p> 
                  {% endif %}
                </div>
            </form>
            {% endif %}
        
            {% if request.user_agent.is_mobile %}
              <form style='height:130px;'></form>
            {% endif %}
          </body>
          <script>
            var input = document.getElementById( 'upload' );
            var infoArea = document.getElementById( 'file-upload-filename' );
        
            input.addEventListener( 'change', showFileName );
        
            function showFileName( event ) {
              
              // the change event gives us the input it occurred in 
              var input = event.srcElement;
              
              // the input has an array of files in the `files` property, each one has a name that you can use. We're just using the name here.
              var fileName = input.files[0].name;
              
              // use fileName however fits your app best, i.e. add it into a div
              infoArea.textContent = 'Selected file: ' + fileName;
            }
        
            var modal = document.getElementById("myModal");
        
            // Get the button that opens the modal
            var btn = document.getElementById("myBtn");
        
            // Get the <span> element that closes the modal
            var span = document.getElementsByClassName("close")[0];
        
            // When the user clicks on the button, open the modal
            btn.onclick = function() {
            modal.style.display = "block";
            }
        
            // When the user clicks on <span> (x), close the modal
            span.onclick = function() {
            modal.style.display = "none";
            }
        
            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
            } 
        
        </script>
        </html>
        

ServerController/templates/users/mail_detail.html
{% load static %}
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <title>INS | '{{ mail.subject }}' Mail </title>
  </head>
    {% include 'navbar.html' %}
    <body class="body-style">
      <form method='POST' class='profile_out_form' style="text-align: left;" enctype="multipart/form-data" >
        <h2 style="text-align: center;">INS Mail</h2>
        
        <p style="width:80px; display: inline-block;">CC:</p>
        {% for m in mail.mail_cc_receiver_set.all %}
          <div class="btn_style_5" style="font-size: 13px;width:max-content ;animation: show-up {{ forloop.counter|div:2 }}s ;" {% if m.DT %}  title="Readed 
{{ m.DT }}"  {% endif %}>
            {{ m.user.username }}
              {% if m.readed %}
                <img src="{% static 'images/readed.png' %}" alt="" width="10px" style="display: inline-block;">
              {% endif %}
          </div>
        {% endfor %}
        <br>

        {% if  mail.username_from == user %}
        <p style="width:80px; display: inline-block;">BCC:</p>
        {% for m in mail.mail_bcc_receiver_set.all %}
          
          <div class="btn_style_5" style="font-size: 13px;width:max-content ;animation: show-up {{ forloop.counter|div:2 }}s ;" {% if m.DT %}  title="Readed 
{{ m.DT }}"  {% endif %}>
            {{ m.user.username }}
              {% if m.readed %}
                <img src="{% static 'images/readed.png' %}" alt="" width="10px" style="display: inline-block;">
              {% endif %}
          </div>
        {% endfor %}
        <br>
        {% endif %}


        <p style="width:80px; display: inline-block;">From:</p> <div class="btn_style_5" style="font-size: 13px;width:max-content ;animation: show-up 0.5s ;"> {{ mail.username_from }} </div><br>
        <p style="width:80px; display: inline-block;">Subject:</p>{{ mail.subject }}
        <p style="text-align:unset;">{{ mail.body|linebreaks }} </p>
        <a style="margin-top: 10px;" class="btn_style_1" href="{% url 'replymail' user_to=mail.username_from.username     subject=mail.subject %}">reply</a>
      </form>
      
    </div>
    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
  </body>
</html>