INSM/urls.py
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import *



urlpatterns = [#add_distribution

    path('INSMHome/'                               , INSMHOME                                , name='INSMHome'                       ),
 
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

INSPP/urls.py
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import *



urlpatterns = [#add_distribution

    path('INSPPHome/'                               , INSPP_home                                , name='INSPPHome'                       ),
    path('INSPPGetData/'                            , INSPP_view_data                           , name='INSPPLogs'                       ),#INSPP_view_update
    path('INSPPGetUpdatedTable/'                    , INSPP_view_update                         , name='INSPP_view_update'               ),
    

    path('AddUnpackedProduct/'                      , AddUnpackedProduct                        , name='AddUnpackedProduct'              ),
    path('AddRawMaterial/'                          , AddRawMaterial                            , name='AddRawMaterial'                  ),
    path('AddRawMaterialInput/'                     , AddRawMaterialsInput                      , name='AddRawMaterialInput'             ),
    path('AddRawMaterialOutput/'                    , AddRawMaterialsOutput                     , name='AddRawMaterialOutput'            ),
    path('AddUnpackedProductRawMaterial/'           , AddUnpackedProductRawMaterial             , name='AddUnpackedProductRawMaterial'   ),
    path('AddPackedProduct/'                        , AddPackedProduct                          , name='AddPackedProduct'                ),
    path('AddPackingMaterial/'                      , AddPackingMaterial                        , name='AddPackingMaterial'              ),
    path('AddPackingMaterialInput/'                 , AddPackingMaterialInput                   , name='AddPackingMaterialInput'         ),
    path('AddPackingMaterialOutput/'                , AddPackingMaterialOutput                  , name='AddPackingMaterialOutput'        ),
    path('AddPackedProductPackingMaterial/'         , AddPackedProductPackingMaterial           , name='AddPackedProductPackingMaterial' ),
    path('AddOrder/'                                , AddOrder                                  , name='AddOrder'                        ),

    path('RawMaterial/<int:pk>/'                    , RawMaterialView.as_view()                 , name='EditRawMaterial'                 ),
    path('PackingMaterial/<int:pk>/'                , PackingMaterialView.as_view()             , name='EditPackingMaterial'             ),
    path('UnpackedProduct/<int:pk>/'                , UnpackedProductView.as_view()             , name='EditUnpackedProduct'             ),
    path('UnpackedProductRawMaterial/<int:pk>/'     , UnpackedProductRawMaterialView.as_view()  , name='EditUnpackedProductRawMaterial'  ),
    path('PackedProduct/<int:pk>/'                  , PackedProductView.as_view()               , name='EditPackedProduct'               ),
    path('PackedProductPackingMaterial/<int:pk>/'   , PackedProductPackingMaterialView.as_view(), name='EditPackedProductPackingMaterial'),
    path('Order/<int:pk>/'                          , OrderView.as_view()                       , name='EditOrder'                       ),

    path('RawMaterials/'                            , RawMaterialsView.as_view()                , name='RawMaterials'                    ),
    path('UnpackedProducts/'                        , UnpackedProductsView.as_view()            , name='UnpackedProducts'                ),
    path('PackedProducts/'                          , PackedProductsView.as_view()              , name='PackedProducts'                  ),
    path('PackingMaterials/'                        , PackingMaterialsView.as_view()            , name='PackingMaterials'                ),
    path('Orders/'                                  , OrdersView.as_view()                      , name='Orders'                          ),


    




]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

INSServer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets



class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)






urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('ServerController.urls')),
    path('', include('INSM.urls')),
    path('', include('INSPP.urls')),
    

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

INSPP/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from decimal import Decimal
import datetime, json
from INSServer import settings




class RawMaterial(models.Model):
    material_types=[
        ('solid','solid'),
        ('liquid','liquid'),
        ('gas','gas')
    ]

    units=[
        ('solid',(
            ('MG','MG'),
            ('CG','CG'),
            ('DG','DG'),
            ('G','G'),
            ('DAG','DAG'),
            ('HG','HG'),
            ('KG','KG'),
            ('T','T'),
            )),
        ('Liquid / Gas',(
            ('ML','ML'),
            ('CL','CL'),
            ('DL','DL'),
            ('L','L'),
            ('DAL','DAL'),
            ('HL','HL'),
            ('KL','KL'))),

    ]

    name                = models.CharField(max_length=200, null=True, blank=True)
    m_type              = models.CharField(max_length=200,choices=material_types)
    code                = models.CharField(max_length=200, null=True, blank=True)
    quantity            = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    unit                = models.CharField(max_length=200,choices=units)
    density             = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    loq_warning         = models.BooleanField(default=0)
    loq_quantity        = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    loq_unit            = models.CharField(max_length=200,choices=units)
    

    def __str__(self):
        return self.name

class RawMaterialsOutput(models.Model):
    units=[
        ('solid',(
            ('MG','MG'),
            ('CG','CG'),
            ('DG','DG'),
            ('G','G'),
            ('DAG','DAG'),
            ('HG','HG'),
            ('KG','KG'),
            ('T','T'),
            )),
        ('Liquid / Gas',(
            ('ML','ML'),
            ('CL','CL'),
            ('DL','DL'),
            ('L','L'),
            ('DAL','DAL'),
            ('HL','HL'),
            ('KL','KL'))),

    ]
    material    = models.ForeignKey(RawMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    quantity    = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    unit        = models.CharField(max_length=200,choices=units)
    date        = models.DateField()
    note        = models.TextField(null=True, blank=True)

class RawMaterialsInput(models.Model):
    units=[
        ('solid',(
            ('MG','MG'),
            ('CG','CG'),
            ('DG','DG'),
            ('G','G'),
            ('DAG','DAG'),
            ('HG','HG'),
            ('KG','KG'),
            ('T','T'),
            )),
        ('Liquid / Gas',(
            ('ML','ML'),
            ('CL','CL'),
            ('DL','DL'),
            ('L','L'),
            ('DAL','DAL'),
            ('HL','HL'),
            ('KL','KL'))),

    ]
    material    = models.ForeignKey(RawMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    quantity    = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    unit        = models.CharField(max_length=200,choices=units)
    date        = models.DateField()
    note        = models.TextField(null=True, blank=True)

class UnpackedProduct(models.Model):
    material_types=[
        ('solid','solid'),
        ('liquid','liquid'),
        ('gas','gas')
    ]

    units=[
        ('Solid',(
            ('MG','MG'),
            ('CG','CG'),
            ('DG','DG'),
            ('G','G'),
            ('DAG','DAG'),
            ('HG','HG'),
            ('KG','KG'),
            ('T','T'),
            )),
        ('Liquid / Gas',(
            ('ML','ML'),
            ('CL','CL'),
            ('DL','DL'),
            ('L','L'),
            ('DAL','DAL'),
            ('HL','HL'),
            ('KL','KL'))),

    ]
    name                = models.CharField(max_length=200, null=True, blank=True)
    code                = models.CharField(max_length=200, null=True, blank=True)
    material_type       = models.CharField(max_length=200,choices=material_types)
    quantity            = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    unit                = models.CharField(max_length=200,choices=units, default=units[0])

    def __str__(self):
        return self.name

class UnpackedProductRawMaterial(models.Model):

    product                 = models.ForeignKey(UnpackedProduct, null=True, blank=True ,on_delete=models.CASCADE)
    material                = models.ForeignKey(RawMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    percent                 = models.DecimalField(decimal_places=3,max_digits=100,default=0)

    def __str__(self):
        return self.product.name+' '+self.material.name

class PackedProduct(models.Model):
    units=[
        ('Solid',(
            ('MG','MG'),
            ('CG','CG'),
            ('DG','DG'),
            ('G','G'),
            ('DAG','DAG'),
            ('HG','HG'),
            ('KG','KG'),
            ('T','T'),
            )),
        ('Liquid / Gas',(
            ('ML','ML'),
            ('CL','CL'),
            ('DL','DL'),
            ('L','L'),
            ('DAL','DAL'),
            ('HL','HL'),
            ('KL','KL'))),

    ]
    name                                = models.CharField(max_length=200, null=True, blank=True)
    code                                = models.CharField(max_length=200, null=True, blank=True)
    unpacked_product                    = models.ForeignKey(UnpackedProduct, null=True, blank=True ,on_delete=models.CASCADE)
    unpacked_product_quantity_in_one    = models.DecimalField(decimal_places=3,max_digits=100,default=0)    
    unit                                = models.CharField(max_length=200,choices=units, default=units[0])

    def __str__(self):
        return self.name

class PackingMaterial(models.Model):
    units=[
        ('Piece','Piece'),
        ('Kilogram','Kilogram'),
        ('Metre','Metre'),
    ]

    name                = models.CharField(max_length=200, null=True, blank=True)
    code                = models.CharField(max_length=200, null=True, blank=True)
    quantity            = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    unit                = models.CharField(max_length=200,choices=units)
    loq_warning         = models.BooleanField(default=0)
    loq_quantity        = models.DecimalField(decimal_places=3,max_digits=100,default=0)

    def __str__(self):
        return self.name

class PackedProductPackingMaterial(models.Model):
    packed_product      = models.ForeignKey(PackedProduct, null=True, blank=True ,on_delete=models.CASCADE)
    packing_material    = models.ForeignKey(PackingMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    count               = models.DecimalField(decimal_places=3,max_digits=100,default=0)


    def __str__(self):
        return self.packed_product.name+' '+self.packing_material.name

class PackingMaterialOutput(models.Model):

    material    = models.ForeignKey(PackingMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    quantity    = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    date        = models.DateField()
    note        = models.TextField(null=True, blank=True)

class PackingMaterialInput(models.Model):
    material    = models.ForeignKey(PackingMaterial, null=True, blank=True ,on_delete=models.CASCADE)
    quantity    = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    date        = models.DateField()
    note        = models.TextField(null=True, blank=True)

class Order(models.Model):
    name                        = models.CharField(max_length=200, null=True, blank=True)
    code                        = models.CharField(max_length=200, null=True, blank=True)
    packed_product              = models.ForeignKey(PackedProduct, null=True, blank=True ,on_delete=models.CASCADE)
    quantity                    = models.DecimalField(decimal_places=3,max_digits=100,default=0)
    starting_date               = models.DateField()
    planned_finishing_date      = models.DateField()
    actual_finishing_date       = models.DateField(null=True, blank=True)
    done                        = models.BooleanField(default=0)


    def __str__(self):
        return self.name


class INSPP_logs(models.Model):
    
    operation       = models.CharField(max_length=200000000, default='[]')
    table           = models.CharField(max_length=200000000, default='[]')
    values          = models.CharField(max_length=200000000, default='[]')
    date_and_time   = models.CharField(max_length=200000000, default='[]')
    distribution    = models.CharField(max_length=200000000, default='[]') # json ids list


    def __str__(self):
        return ('['+self.operation +']      '+ self.table +'    '+ self.values)

material_units_convert={
    'MG'    :0.001
    ,'CG'   :0.01
    ,'DG'   :0.1
    ,'G'    :1
    ,'DAG'  :10
    ,'HG'   :100
    ,'KG'   :1000
    ,'T'    :1000000
    
    ,'ML'   :0.001
    ,'CL'   :0.01
    ,'DL'   :0.1
    ,'L'    :1
    ,'DAL'  :10
    ,'HL'   :100
    ,'KL'   :1000

}

base_unit={
    'MG'    :('G','Solid')
    ,'CG'   :('G','Solid')
    ,'DG'   :('G','Solid')
    ,'G'    :('G','Solid')
    ,'DAG'  :('G','Solid')
    ,'HG'   :('G','Solid')
    ,'KG'   :('G','Solid')
    ,'T'    :('G','Solid')
    
    ,'ML'   :('L','Liquid')
    ,'CL'   :('L','Liquid')
    ,'DL'   :('L','Liquid')
    ,'L'    :('L','Liquid')
    ,'DAL'  :('L','Liquid')
    ,'HL'   :('L','Liquid')
    ,'KL'   :('L','Liquid')
}

material_types={
    'solid' :['MG','CG','DG','G','DAG','HG','KG','T'],
    'liquid':['ML','CL','DL','L','DAL','HL','KL'],
    'gas'   :['ML','CL','DL','L','DAL','HL','KL'],
    }


def convert_to_best_unit(value,unit,m_type):
    units=material_types[m_type.lower()]
    while True :
        if float(value)>=10 and units.index(unit)<len(units)-1 and unit.upper()!='KG':
            value=value/10

INSPP/templates/INSPP/order_detail.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel=icon href="{% static 'images/INSPP logo.png' %}" sizes="16x16" type="image/png">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <title>INSS | {{ form.name.value }} Order </title>
  </head>
  {% include 'navbar.html' %}
          <body class="body-style">
    <form class="profile_out_form" method="POST" style="text-align: left;">
        <h2 style="text-align: center;">{{ form.name.value }} Order</h2>
        {% csrf_token %}
        <p style="width: 30%; display: inline-block;text-align: right;"> Name:   </p>{{ form.name|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Code:  </p>{{ form.code|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Packed product:  </p>{{ form.packed_product|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Quantity:  </p>{{ form.quantity|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Starting date: </p>{{ form.starting_date|add_class:"field-style-5" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Planned finishing date:  </p>{{ form.planned_finishing_date|add_class:"field-style-5" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Actual finished date:  </p>{{ form.actual_finishing_date|add_class:"field-style-5" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Done:  </p>{{ form.done }} <br>
        
        
        <button type="submit" class="btn_style_1" name="edit" value="Edit" style="display: inline-block;"><img src="{% static 'inspp-icons/edit.png' %}" alt="Add raw material" style="width: 30px;"></button>
        <div class="btn_style_1" id="myBtn" style="width: 30px;display: inline-block;"><img src="{% static 'inspp-icons/delete.png' %}" alt="Add raw material" style="width: 30px;"></div>
        <div id="myModal" class="modal">
          <div class="modal-content profile_out_form">
            <span class="close">&times;</span>
            <p>Are you sure Do you wannt to delete this?</p>
            <button type="submit" class="btn_style_1" name="delete" value="Delete" >YES</button>
          </div>
        </div>

        
    </form>

    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
  </body>
  <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    } 
  </script>
</html>

INSPP/templates/INSPP/order_list.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel=icon href="{% static 'images/INSPP logo.png' %}" sizes="16x16" type="image/png">
        <link rel="stylesheet" href="{% static 'style/main.css' %}">
        <title>INS | Orders </title>
    </head>
    {% include 'navbar.html' %}
    <body class="body-style">
        <div>
            <div style=" display: inline-block;width: 100%;">
                <div style="display: inline-block; width: 95%;color: white;right: 0; ">
                    <div id="Raw materials" class="tabcontent" >
                        <h1 class="typing-text-2">Orders</h1>
                        <div style="width: 100%;text-align: right;">
                            <a  href="{% url 'AddOrder' %}"><img src="{% static 'inspp-icons/add.png' %}" alt="Add Order" style="width: 30px;margin-bottom:20px;"></a>
                        </div>
                        {% for material in Orders %}
                            <div class="list_item"  onclick="location.href='{% url 'EditOrder' material.id %}';">
                                <p>{{ material }}</p> 
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% include 'pages-tabs.html' %}
    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
    </body>
</html>

INSPP/templates/INSPP/packedproduct_detail.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <link rel=icon href="{% static 'images/INSPP logo.png' %}" sizes="16x16" type="image/png">
    <title>INS | {{ form.name.value }} Packed Product </title>
  </head>
  {% include 'navbar.html' %}
          <body class="body-style">
    <form class="profile_out_form" method="POST" style="text-align: left;">
        <h2 style="text-align: center;">{{ form.name.value }} Packed Product</h2>
        {% csrf_token %}
        <p style="width: 30%; display: inline-block;text-align: right;"> Name:   </p>{{ form.name|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Code:  </p>{{ form.code|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Unpacked product:  </p>{{ form.unpacked_product|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Quantity:  </p>{{ form.unpacked_product_quantity_in_one|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Unit: </p>{{ form.unit|add_class:"field-style-2" }} <br>
        <button type="submit" class="btn_style_1" name="edit" value="Edit" style="display: inline-block;"><img src="{% static 'inspp-icons/edit.png' %}" alt="Add raw material" style="width: 30px;"></button>
        <div class="btn_style_1" id="myBtn" style="width: 30px;display: inline-block;"><img src="{% static 'inspp-icons/delete.png' %}" alt="Add raw material" style="width: 30px;"></div>
        <div id="myModal" class="modal">
          <div class="modal-content profile_out_form">
            <span class="close">&times;</span>
            <p>Are you sure Do you wannt to delete this?</p>
            <button type="submit" class="btn_style_1" name="delete" value="Delete" >YES</button>
          </div>
        </div>


        <h2 style="text-align: center;">Raw materials</h2>

        {% for material in object.packedproductpackingmaterial_set.all %}
          <div class="list_item" style="background-color: #0e1621;" onclick="location.href='{% url 'EditPackedProductPackingMaterial' material.id %}';">
            <p>{{ material.packing_material.name }} ({{ material.count }} {{ material.packing_material.unit }})</p> 
          </div>
        {% endfor %}
    </form>





    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
  </body>
  <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    } 
  </script>
</html>

INSPP/templates/INSPP/packedproduct_list.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel=icon href="{% static 'images/INSPP logo.png' %}" sizes="16x16" type="image/png">
        <link rel="stylesheet" href="{% static 'style/main.css' %}">
        <title>INS | Packed Products </title>
    </head>
    {% include 'navbar.html' %}
          <body class="body-style">
        <div>
            <div style=" display: inline-block;width: 100%;">
                <div style="display: inline-block; width: 95%;color: white;right: 0; ">
                    <div id="Raw materials" class="tabcontent" >
                        <h1 class="typing-text-2">Packed Products</h1>
                        <div style="width: 100%;text-align: right;">
                            <a href="{% url 'AddPackedProduct' %}"><img src="{% static 'inspp-icons/add.png' %}" alt="Add Packed Product" style="width: 30px;margin-bottom:20px;"></a>
                        </div>
                        {% for material in PackedProducts %}
                            <div class="list_item"  onclick="location.href='{% url 'EditPackedProduct' material.id %}';">
                                <p>{{ material }}</p> 
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% include 'pages-tabs.html' %}
    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
    </body>
</html>

INSPP/templates/INSPP/packedproductpackingmaterial_detail.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel=icon href="{% static 'images/INSPP logo.png' %}" sizes="16x16" type="image/png">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <title>INS | Packed Product Raw Material </title>
  </head>
  {% include 'navbar.html' %}
  <body class="body-style">
    <form class="profile_out_form" method="POST" style="text-align: left;">
        <h2 style="text-align: center;"> Packed Product Packing Material</h2>
        {% csrf_token %}
        <p style="width: 30%; display: inline-block;text-align: right;"> Packed product:   </p>{{ form.packed_product|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Packing material:  </p>{{ form.packing_material|add_class:"field-style-2" }} <br>
        <p style="width: 30%; display: inline-block;text-align: right;"> Count:  </p>{{ form.count|add_class:"field-style-2" }} <br>
        
        <button type="submit" class="btn_style_1" name="edit" value="Edit" style="display: inline-block;"><img src="{% static 'inspp-icons/edit.png' %}" alt="Add raw material" style="width: 30px;"></button>
        <div class="btn_style_1" id="myBtn" style="width: 30px;display: inline-block;"><img src="{% static 'inspp-icons/delete.png' %}" alt="Add raw material" style="width: 30px;"></div>
        <div id="myModal" class="modal">
          <div class="modal-content profile_out_form">
            <span class="close">&times;</span>
            <p>Are you sure Do you wannt to delete this?</p>
            <button type="submit" class="btn_style_1" name="delete" value="Delete" >YES</button>
          </div>
        </div>

        
    </form>

    {% if request.user_agent.is_mobile %}
      <form style='height:130px;'></form>
    {% endif %}
  </body>
  <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    } 
  </script>
</html>